name: Encrypt Google Cloud JSON Token

on:
  push:
    branches:
      - master  # Adjust branch name as needed

jobs:
  encrypt-token:
    name: Build and push to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_SECRET }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: 'gcloud info'

