name: Encrypt Google Cloud JSON Token

on:
  push:
    branches:
      - master  # Adjust branch name as needed

jobs:
  encrypt-token:
    name: Build and push to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_SECRET }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Use gcloud CLI
        run: gcloud info
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
#      - name: Build,push & tag client Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: ./client
#          load: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/react-test
#          file: ./client/Dockerfile.dev
#      - name: Run Docker Run
#        run: |
#          docker run ${{ secrets.DOCKER_USERNAME }}/react-test npm test -- --coverage
#      - name: Build,push & tag client Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: ./client
#          platforms: linux/amd64
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/multi-client:${{ github.sha }} ,${{ secrets.DOCKER_USERNAME }}/multi-client:latest
#          file: ./client/Dockerfile
#      - name: Build,push & tag server Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: ./server
#          platforms: linux/amd64
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/multi-server:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/multi-server:latest
#          file: ./server/Dockerfile
#      - name: Build,push & tag worker Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: ./worker
#          platforms: linux/amd64
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/multi-worker:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/multi-worker:latest
#          file: ./worker/Dockerfile
      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY }}
      - name: Pull Docker Image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/multi-client:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/multi-server:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/multi-worker:latest
      - name: Tag Docker Image for GCR
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/multi-client:latest ${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/multi-client:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/multi-server:latest ${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/multi-server:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/multi-worker:latest ${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/multi-worker:latest
      - name: Push Docker Image to GCR
        run: |
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/multi-client:latest
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/multi-server:latest
          docker push ${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/multi-worker:latest
      - id: get-credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: multi-cluster
          location: asia-southeast1-b
      - name: Run Kubectl apply
        run: |
          kubectl apply -f k8s
          kubectl set image deployments/client-deployment client=${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/multi-client:latest
          kubectl set image deployments/server-deployment server=${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/multi-server:latest
          kubectl set image deployments/worker-deployment worker=${{ secrets.ARTIFACT_REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ secrets.REPO_NAME }}/multi-worker:latest

